name: Cinematics
version: ${project.version}
main: it.mattsays.cinematics.Cinematics
api-version: 1.16
authors: [ MattSaysMC ]
commands:
  animations:
    description: Manages animations
    usage: /animations <play:stop:visualize:list:reload>