name: Cinematics
version: ${project.version}
main: it.mattsays.cinematics.Cinematics
api-version: 1.16
authors: [ MattSaysMC ]
commands:
  animcreator:
    description: Creates animations
    usage: /animcreator <add:finish:play:stop>