# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - id: set-nms-version
      run: echo ::set-output name=nms-version::1.16.5
    - name: Cache NMS
      id: cache-nms
      uses: actions/cache@v1
      with:
        path: nms-build/.m2/repository/
        key: ${{ runner.os }}-${{ steps.set-nms-version.outputs.nms-version }}-nms
    - name: Build NMS
      if: steps.cache-nms.outputs.cache-hit != 'true'
      uses: derongan/nmsaction@v1
      with:
        rev: ${{ steps.set-nms-version.outputs.nms-version }}
    - name: Install nms into m2
      run: mkdir -p $HOME/.m2/repository && cp -a nms-build/.m2/repository/* $HOME/.m2/repository
    - name: Build with Maven
      run: mvn -B package --file pom.xml
