# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - id: set-nms-version
      run: echo ::set-output name=nms-version::1.16.5
    - name: Cache NMS
      id: cache-nms
      uses: actions/cache@v1
      with:
        path: nms-build/.m2/repository/
        key: ${{ runner.os }}-${{ steps.set-nms-version.outputs.nms-version }}-nms
    - name: Build NMS
      if: steps.cache-nms.outputs.cache-hit != 'true'
      uses: derongan/nmsaction@v1
      with:
        rev: ${{ steps.set-nms-version.outputs.nms-version }}
    - name: Install nms into m2
      run: mkdir -p $HOME/.m2/repository && cp -a nms-build/.m2/repository/* $HOME/.m2/repository
    - name: Cache dependecies
      uses: actions/cache@v1
      with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cinematics
        path: target/Cinematics*.jar
    - name: Copy artifact to main dir
      uses: canastro/copy-file-action@master
      with:
        source: "target/Cinematics*.jar"
        target: "Cinematics.jar"
    - name: Copy artifact to dev server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "Cinematics.jar"
        target: ${{ secrets.TARGET_DIR }}
